name: Build and Deploy (Staging Only)

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: staging
      DOTENV_PATH: .env.staging
      MONITOR_ID: '41776000000276110'
      HOST: ${{ secrets.HOST_STAG }}
      REMOTE_PATH: '/home/ubuntu/test-code'
      ARTIFACT_PATH: '/home/ubuntu/test-code'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.14.0"
      - name: Install Dependencies
        run: |
           unset CI
           npm install --frozen-lockfile

      - name: Run Staging Build
        env:
          DOTENV_CONFIG_PATH: .env.staging
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          CI='' npm run build:staging
          if [ -d "dist" ]; then
            echo "Staging build completed successfully."
          else
            echo "::error::Build failed: 'Build' directory not found."
            exit 1
          fi
      - name: Create full project artifact
        run: |
         cd ../
         tar -zcf guest-connect-survey-form.tar.gz guest-connect-survey-form
      - name: Transfer build to remote server
        run: |
          cd ../
          echo "${{ secrets.KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem /home/runner/work/guest-connect-survey-form/guest-connect-survey-form.ai.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST_STAG }}:${{ env.ARTIFACT_PATH }}
          rm -f private_key.pem
      
